"""empty message

Revision ID: ab81d22883ea
Revises: 
Create Date: 2020-06-17 22:24:48.342370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab81d22883ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anredecode', sa.Integer(), nullable=False),
    sa.Column('titel', sa.String(length=40), nullable=True),
    sa.Column('familienname', sa.String(length=40), nullable=False),
    sa.Column('vorname', sa.String(length=40), nullable=True),
    sa.Column('notiz', sa.String(length=200), nullable=True),
    sa.Column('kunde', sa.Boolean(), nullable=False),
    sa.Column('adr_strasse', sa.String(length=50), nullable=True),
    sa.Column('adr_plz', sa.String(length=40), nullable=True),
    sa.Column('adr_ort', sa.String(length=50), nullable=True),
    sa.Column('kontakte', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiername', sa.String(length=30), nullable=False),
    sa.Column('tierart', sa.String(length=30), nullable=True),
    sa.Column('rasse', sa.String(length=30), nullable=True),
    sa.Column('farbe', sa.String(length=30), nullable=True),
    sa.Column('viren', sa.String(length=50), nullable=True),
    sa.Column('merkmal', sa.String(length=50), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=False),
    sa.Column('geschlechtscode', sa.Integer(), nullable=False),
    sa.Column('chip_nummer', sa.String(length=30), nullable=True),
    sa.Column('eu_passnummer', sa.String(length=30), nullable=True),
    sa.Column('patient', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_password'), 'user', ['password'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('behandlung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('gewicht', sa.String(length=50), nullable=True),
    sa.Column('diagnose', sa.String(length=2000), nullable=True),
    sa.Column('laborwerte1', sa.String(length=1000), nullable=True),
    sa.Column('laborwerte2', sa.String(length=1000), nullable=True),
    sa.Column('arzneien', sa.String(length=256), nullable=True),
    sa.Column('arzneimittel', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behandlung_tier_id'), 'behandlung', ['tier_id'], unique=False)
    op.create_table('behandlungsverlauf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('diagnose', sa.String(length=256), nullable=True),
    sa.Column('behandlung', sa.String(length=4000), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behandlungsverlauf_person_id'), 'behandlungsverlauf', ['person_id'], unique=False)
    op.create_index(op.f('ix_behandlungsverlauf_tier_id'), 'behandlungsverlauf', ['tier_id'], unique=False)
    op.create_table('rechnung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('lfnr', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('ort', sa.String(length=256), nullable=True),
    sa.Column('diagnose', sa.String(length=256), nullable=True),
    sa.Column('bezahlung', sa.String(length=256), nullable=True),
    sa.Column('brutto_summe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('netto_summe', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('steuerbetrag_zwanzig', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('steuerbetrag_dreizehn', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('steuerbetrag_zehn', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rechnung_person_id'), 'rechnung', ['person_id'], unique=False)
    op.create_index(op.f('ix_rechnung_tier_id'), 'rechnung', ['tier_id'], unique=False)
    op.create_table('tierhaltung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['tier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tierhaltung_person_id'), 'tierhaltung', ['person_id'], unique=False)
    op.create_index(op.f('ix_tierhaltung_tier_id'), 'tierhaltung', ['tier_id'], unique=False)
    op.create_table('impfung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('behandlung_id', sa.Integer(), nullable=False),
    sa.Column('impfungscode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behandlung_id'], ['behandlung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impfung_behandlung_id'), 'impfung', ['behandlung_id'], unique=False)
    op.create_table('rechnungszeile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rechnung_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('artikelcode', sa.Integer(), nullable=False),
    sa.Column('artikel', sa.String(length=256), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['rechnung_id'], ['rechnung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rechnungszeile_rechnung_id'), 'rechnungszeile', ['rechnung_id'], unique=False)
    op.create_table('termin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tierhaltung_id', sa.Integer(), nullable=True),
    sa.Column('autor', sa.String(length=30), nullable=True),
    sa.Column('beginn', sa.DateTime(), nullable=False),
    sa.Column('ende', sa.DateTime(), nullable=False),
    sa.Column('thema', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tierhaltung_id'], ['tierhaltung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_termin_tierhaltung_id'), 'termin', ['tierhaltung_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_termin_tierhaltung_id'), table_name='termin')
    op.drop_table('termin')
    op.drop_index(op.f('ix_rechnungszeile_rechnung_id'), table_name='rechnungszeile')
    op.drop_table('rechnungszeile')
    op.drop_index(op.f('ix_impfung_behandlung_id'), table_name='impfung')
    op.drop_table('impfung')
    op.drop_index(op.f('ix_tierhaltung_tier_id'), table_name='tierhaltung')
    op.drop_index(op.f('ix_tierhaltung_person_id'), table_name='tierhaltung')
    op.drop_table('tierhaltung')
    op.drop_index(op.f('ix_rechnung_tier_id'), table_name='rechnung')
    op.drop_index(op.f('ix_rechnung_person_id'), table_name='rechnung')
    op.drop_table('rechnung')
    op.drop_index(op.f('ix_behandlungsverlauf_tier_id'), table_name='behandlungsverlauf')
    op.drop_index(op.f('ix_behandlungsverlauf_person_id'), table_name='behandlungsverlauf')
    op.drop_table('behandlungsverlauf')
    op.drop_index(op.f('ix_behandlung_tier_id'), table_name='behandlung')
    op.drop_table('behandlung')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_password'), table_name='user')
    op.drop_table('user')
    op.drop_table('tier')
    op.drop_table('person')
    # ### end Alembic commands ###
